# Generated by Django 2.2.5 on 2019-09-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4e', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
