# Generated by Django 2.2.5 on 2019-09-07 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('d4e', '0002_auto_20190907_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
