# Generated by Django 2.2.5 on 2019-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4e', '0003_tags_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=True, to='d4e.Article')),
            ],
        ),
    ]
