# Generated by Django 2.2.5 on 2019-10-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d4e', '0005_auto_20190907_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
