# Generated by Django 3.0.5 on 2020-06-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('delete_flag', models.IntegerField(default=0, editable=False)),
                ('dict_code', models.CharField(max_length=20, verbose_name='字典码')),
                ('dict_desc', models.CharField(max_length=32, verbose_name='字典项')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'db_table': 'sys_dict',
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('delete_flag', models.IntegerField(default=0, editable=False)),
                ('type_code', models.CharField(max_length=20, verbose_name='字典类型码')),
                ('type_desc', models.CharField(max_length=32, verbose_name='字典类型描述')),
            ],
            options={
                'verbose_name': '数据字典类型',
                'verbose_name_plural': '数据字典类型',
                'db_table': 'sys_dict_type',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('delete_flag', models.IntegerField(default=0, editable=False)),
                ('link', models.CharField(max_length=64, verbose_name='连接')),
                ('desc', models.CharField(max_length=32, verbose_name='描述')),
            ],
            options={
                'verbose_name': '友情连接',
                'verbose_name_plural': '友情连接',
                'db_table': 'sys_link',
            },
        ),
    ]
