# Generated by Django 2.2.6 on 2019-10-11 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('delete_flag', models.IntegerField()),
                ('dict_code', models.CharField(max_length=20)),
                ('dict_desc', models.CharField(max_length=32)),
                ('create_user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '数据字典',
                'db_table': 'sys_dict',
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('delete_flag', models.IntegerField()),
                ('type_code', models.CharField(max_length=20)),
                ('type_desc', models.CharField(max_length=32)),
                ('create_user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '数据字典类型',
                'db_table': 'sys_dict_type',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('delete_flag', models.IntegerField()),
                ('link', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=32)),
                ('create_user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '友情连接',
                'db_table': 'sys_link',
            },
        ),
        migrations.DeleteModel(
            name='Common',
        ),
        migrations.AddField(
            model_name='dict',
            name='dict_type',
            field=models.ForeignKey(on_delete=True, to='common.DictType'),
        ),
    ]
