# Generated by Django 2.2.6 on 2019-10-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191011_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict',
            options={'verbose_name': '数据字典', 'verbose_name_plural': '数据字典'},
        ),
        migrations.AlterModelOptions(
            name='dicttype',
            options={'verbose_name': '数据字典类型', 'verbose_name_plural': '数据字典类型'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友情连接', 'verbose_name_plural': '友情连接'},
        ),
        migrations.AlterField(
            model_name='dict',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dict',
            name='dict_code',
            field=models.CharField(max_length=20, verbose_name='字典码'),
        ),
        migrations.AlterField(
            model_name='dict',
            name='dict_desc',
            field=models.CharField(max_length=32, verbose_name='字典项'),
        ),
        migrations.AlterField(
            model_name='dict',
            name='dict_type',
            field=models.ForeignKey(on_delete=True, to='common.DictType', verbose_name='字典类型'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='type_code',
            field=models.CharField(max_length=20, verbose_name='字典类型码'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='type_desc',
            field=models.CharField(max_length=32, verbose_name='字典类型描述'),
        ),
        migrations.AlterField(
            model_name='link',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='desc',
            field=models.CharField(max_length=32, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=64, verbose_name='连接'),
        ),
    ]
