# Generated by Django 2.2.6 on 2019-10-11 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191011_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='delete_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
