# Generated by Django 2.2.6 on 2019-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191011_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
    ]
