# Generated by Django 2.2.6 on 2019-10-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191011_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
