# Generated by Django 2.2.6 on 2019-10-11 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.AddField(
            model_name='articles',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='delete_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='delete_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='delete_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='delete_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
