# Generated by Django 2.2.6 on 2019-10-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191011_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': '文章类型', 'verbose_name_plural': '文章类型'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tags',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='delete_flag',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
